### PR TITLE
Quick simplification of Gibbs_phase

### PR DESCRIPTION
**Pull request by bsaund**
Simplify Gibbs_phase and Gibbs_phase2.
This could be taken further.
Mostly this is an easy change for a first "pull request"

### CODE REVIEW

**Comment by skbirner** [comment]
Cool, thanks! The code is definitely super inefficiently written right now. You can can see that most of the plots are written with random scales and then stretched to look correct on top of each other. Obviously this won't work well when I need to make complicated plots that are quantitative rather than qualitative, so I think my next step is to write a little plot function. Ideally it will let me scale things properly and also keep me from copying the current plotting code over and over.

**Comment by bsaund** [comment]
Sounds good.
It was honestly scary for me at first having my code reviewed. I knew my
code wasn't perfect but hearing the critiques felt like an attack on me.
(Okay, a bit extreme, but that was the similar feeling). Perhaps this just
shows how insecure I was at coding. After a few months though I started to
really appreciate the feedback.

On Mon, Sep 21, 2015 at 10:57 PM, skbirner notifications@github.com wrote:

> Cool, thanks! The code is definitely super inefficiently written right
> now. You can can see that most of the plots are written with random scales
> and then stretched to look correct on top of each other. Obviously this
> won't work well when I need to make complicated plots that are quantitative
> rather than qualitative, so I think my next step is to write a little plot
> function. Ideally it will let me scale things properly and also keep me
> from copying the current plotting code over and over.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142167092
> .

## 

Brad Saund

**Comment by skbirner** [comment]
Yeah, I know the feeling. It helped a bit, actually, that I knew my code was messy, so it didn't bother me much to get feedback-- it's scarier presenting code that you're really proud of, because then you feel a lot worse about the criticisms.

Have you heard of or worked with JSXGraph at all (http://jsxgraph.uni-bayreuth.de/wp/)? It looks like it might be a nicer way to do interactive Javascript plots. I'm having a difficult time coming up with nice, succinct ways to plot multiple functions in normal Javascript that don't require copy-pasting large amounts of essentially duplicate code. There are too many inputs to have it work nicely as a function, and Javascript doesn't seem to have classes. The way you guys did it (using a var with methods to build and redraw the data) seems to be the best way, but unless I'm mistaken, it still requires redefining all those methods each and every time you want to plot something.

**Comment by bsaund** [comment]
I have not heard of JSXGraph.
I don't know how to plot things in "normal Javascript". This code uses d3.
You can see the <script> (kind of like an import in other languages) at the
top of "index_copy.html".
Matt had all the plotting working before I started. I altered some things,
but mostly I used what he had.

Javascript does not have classes, and I am not really sure the "best" way
to get that behavior. You can see I played around with a few different
ways. One way is with "var" as you mentioned. You can also do some stuff
with functions. Search for "BuildingDialog" in my code, and notice I create
a new instance with the "new" keyword.

Repeating lots of code is bad. I think there is a way to do it without
redefining all the methods every time, at least not explicitly. Let me take
a look and I'll create another pull request.

On Tue, Sep 22, 2015 at 6:11 PM, skbirner notifications@github.com wrote:

> Yeah, I know the feeling. It helped a bit, actually, that I knew my code
> was messy, so it didn't bother me much to get feedback-- it's scarier
> presenting code that you're really proud of, because then you feel a lot
> worse about the criticisms.
> 
> Have you heard of or worked with JSXGraph at all (
> http://jsxgraph.uni-bayreuth.de/wp/)? It looks like it might be a nicer
> way to do interactive Javascript plots. I'm having a difficult time coming
> up with nice, succinct ways to plot multiple functions in normal Javascript
> that don't require copy-pasting large amounts of essentially duplicate
> code. There are too many inputs to have it work nicely as a function, and
> Javascript doesn't seem to have classes. The way you guys did it (using a
> var with methods to build and redraw the data) seems to be the best way,
> but unless I'm mistaken, it still requires redefining all those methods
> each and every time you want to plot something.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142436668
> .

## 

Brad Saund

**Comment by skbirner** [comment]
Yeah, sorry, when I said ‘normal Javascript’, I meant Javascript with d3 imported, as the code currently uses— I suppose I should have said “without importing another library” to be more technically correct. The d3 library does not seem to have simple support for reusable charts, based on the fact that (a) example d3 plots all involve creating new variables each time, (b) there are blog posts complaining about this problem, and (c) there are a bunch of additional libraries, either stand-alone or built on d3, that aim to improve this situation. So I’m guessing my best bet will be to use something like JSXGraph, given that their codes for plotting functions are succinct, allow interactive plots, and look easy to implement.

I have seen a few ways to get around some of my issues by using functions as pseudo-classes (such as the slider() function in the pdControl code, which is essentially creating a slider class). I think the best way to do this would be to create a plot() function that takes in a function name and maybe x and y limits, and then has defined methods to deal with changing the position, color, etc, of the graph. My original plan was to try to turn your code for the var stepResponse into such a function, but ended up getting frustrated and googling for better solutions. I may play around more with that concept— however I’m guessing that a pre-made package has most likely already done this more eloquently and functionally than I ever could (though writing something myself is certainly still a good learning experience).

On Sep 22, 2015, at 3:51 PM, bsaund <notifications@github.com<mailto:notifications@github.com>> wrote:

I have not heard of JSXGraph.
I don't know how to plot things in "normal Javascript". This code uses d3.
You can see the <script> (kind of like an import in other languages) at the
top of "index_copy.html".
Matt had all the plotting working before I started. I altered some things,
but mostly I used what he had.

Javascript does not have classes, and I am not really sure the "best" way
to get that behavior. You can see I played around with a few different
ways. One way is with "var" as you mentioned. You can also do some stuff
with functions. Search for "BuildingDialog" in my code, and notice I create
a new instance with the "new" keyword.

Repeating lots of code is bad. I think there is a way to do it without
redefining all the methods every time, at least not explicitly. Let me take
a look and I'll create another pull request.

On Tue, Sep 22, 2015 at 6:11 PM, skbirner <notifications@github.com<mailto:notifications@github.com>> wrote:

> Yeah, I know the feeling. It helped a bit, actually, that I knew my code
> was messy, so it didn't bother me much to get feedback-- it's scarier
> presenting code that you're really proud of, because then you feel a lot
> worse about the criticisms.
> 
> Have you heard of or worked with JSXGraph at all (
> http://jsxgraph.uni-bayreuth.de/wp/)? It looks like it might be a nicer
> way to do interactive Javascript plots. I'm having a difficult time coming
> up with nice, succinct ways to plot multiple functions in normal Javascript
> that don't require copy-pasting large amounts of essentially duplicate
> code. There are too many inputs to have it work nicely as a function, and
> Javascript doesn't seem to have classes. The way you guys did it (using a
> var with methods to build and redraw the data) seems to be the best way,
> but unless I'm mistaken, it still requires redefining all those methods
> each and every time you want to plot something.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142436668
> .

## 

Brad Saund

**Comment by bsaund** [comment]
Hmm, I think you should have gotten another email about a pull-request. I
was expected to get one also...Guess not?

As you can see we had the same idea for a "plot" function. You don't even
have to define functions for new things like color. You can just use the
.css like normal.

I've gotten pretty frustrated googling for some javascript solutions
before. Maybe I just don't understand javascript that well, but it seems to
me that there is a lot of information on Javascript, but when googling
sometimes it is hard to find a related answer and sometimes the people
answering are dumb. This seems more true for javascript than other
languages I've worked with.

I agree a package _may_ be better thought out, more robust, faster, sexier,
better for the environment, etc. It also comes with the cost of learning a
new interface, and the possibility of investing a bunch of time before
deciding it is crap. Up to you.

On Tue, Sep 22, 2015 at 8:08 PM, skbirner notifications@github.com wrote:

> Yeah, sorry, when I said ‘normal Javascript’, I meant Javascript with d3
> imported, as the code currently uses— I suppose I should have said “without
> importing another library” to be more technically correct. The d3 library
> does not seem to have simple support for reusable charts, based on the fact
> that (a) example d3 plots all involve creating new variables each time, (b)
> there are blog posts complaining about this problem, and (c) there are a
> bunch of additional libraries, either stand-alone or built on d3, that aim
> to improve this situation. So I’m guessing my best bet will be to use
> something like JSXGraph, given that their codes for plotting functions are
> succinct, allow interactive plots, and look easy to implement.
> 
> I have seen a few ways to get around some of my issues by using functions
> as pseudo-classes (such as the slider() function in the pdControl code,
> which is essentially creating a slider class). I think the best way to do
> this would be to create a plot() function that takes in a function name and
> maybe x and y limits, and then has defined methods to deal with changing
> the position, color, etc, of the graph. My original plan was to try to turn
> your code for the var stepResponse into such a function, but ended up
> getting frustrated and googling for better solutions. I may play around
> more with that concept— however I’m guessing that a pre-made package has
> most likely already done this more eloquently and functionally than I ever
> could (though writing something myself is certainly still a good learning
> experience).
> 
> On Sep 22, 2015, at 3:51 PM, bsaund <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> I have not heard of JSXGraph.
> I don't know how to plot things in "normal Javascript". This code uses d3.
> You can see the <script> (kind of like an import in other languages) at
> the
> top of "index_copy.html".
> Matt had all the plotting working before I started. I altered some things,
> but mostly I used what he had.
> 
> Javascript does not have classes, and I am not really sure the "best" way
> to get that behavior. You can see I played around with a few different
> ways. One way is with "var" as you mentioned. You can also do some stuff
> with functions. Search for "BuildingDialog" in my code, and notice I
> create
> a new instance with the "new" keyword.
> 
> Repeating lots of code is bad. I think there is a way to do it without
> redefining all the methods every time, at least not explicitly. Let me
> take
> a look and I'll create another pull request.
> 
> On Tue, Sep 22, 2015 at 6:11 PM, skbirner <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> 
> > Yeah, I know the feeling. It helped a bit, actually, that I knew my code
> > was messy, so it didn't bother me much to get feedback-- it's scarier
> > presenting code that you're really proud of, because then you feel a lot
> > worse about the criticisms.
> > 
> > Have you heard of or worked with JSXGraph at all (
> > http://jsxgraph.uni-bayreuth.de/wp/)? It looks like it might be a nicer
> > way to do interactive Javascript plots. I'm having a difficult time
> > coming
> > up with nice, succinct ways to plot multiple functions in normal
> > Javascript
> > that don't require copy-pasting large amounts of essentially duplicate
> > code. There are too many inputs to have it work nicely as a function,
> > and
> > Javascript doesn't seem to have classes. The way you guys did it (using
> > a
> > var with methods to build and redraw the data) seems to be the best way,
> > but unless I'm mistaken, it still requires redefining all those methods
> > each and every time you want to plot something.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/skbirner/thermo-website/pull/1#issuecomment-142436668>
> > .
> 
> ## 
> 
> Brad Saund
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142443277>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142457999
> .

## 

Brad Saund

**Comment by skbirner** [comment]
Yup, got the email! That looks about like what I was going for in terms of a function, thanks. I guess it’s true that I can do formatting stuff through .css, and then I don’t have an obscene number of inputs.

I’ve also had a hard time googling solutions in Javascript. I went through most of the w3schools Javascript stuff, which was all fairly basic. Certainly useful for understanding the basics, but not very helpful for answering any of my actual questions.

I’ll play around a bit with both the function and the package, and see which seems most useful in the long run. Thanks again!

On Sep 22, 2015, at 5:42 PM, bsaund <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm, I think you should have gotten another email about a pull-request. I
was expected to get one also...Guess not?

As you can see we had the same idea for a "plot" function. You don't even
have to define functions for new things like color. You can just use the
.css like normal.

I've gotten pretty frustrated googling for some javascript solutions
before. Maybe I just don't understand javascript that well, but it seems to
me that there is a lot of information on Javascript, but when googling
sometimes it is hard to find a related answer and sometimes the people
answering are dumb. This seems more true for javascript than other
languages I've worked with.

I agree a package _may_ be better thought out, more robust, faster, sexier,
better for the environment, etc. It also comes with the cost of learning a
new interface, and the possibility of investing a bunch of time before
deciding it is crap. Up to you.

On Tue, Sep 22, 2015 at 8:08 PM, skbirner <notifications@github.com<mailto:notifications@github.com>> wrote:

> Yeah, sorry, when I said ‘normal Javascript’, I meant Javascript with d3
> imported, as the code currently uses— I suppose I should have said “without
> importing another library” to be more technically correct. The d3 library
> does not seem to have simple support for reusable charts, based on the fact
> that (a) example d3 plots all involve creating new variables each time, (b)
> there are blog posts complaining about this problem, and (c) there are a
> bunch of additional libraries, either stand-alone or built on d3, that aim
> to improve this situation. So I’m guessing my best bet will be to use
> something like JSXGraph, given that their codes for plotting functions are
> succinct, allow interactive plots, and look easy to implement.
> 
> I have seen a few ways to get around some of my issues by using functions
> as pseudo-classes (such as the slider() function in the pdControl code,
> which is essentially creating a slider class). I think the best way to do
> this would be to create a plot() function that takes in a function name and
> maybe x and y limits, and then has defined methods to deal with changing
> the position, color, etc, of the graph. My original plan was to try to turn
> your code for the var stepResponse into such a function, but ended up
> getting frustrated and googling for better solutions. I may play around
> more with that concept— however I’m guessing that a pre-made package has
> most likely already done this more eloquently and functionally than I ever
> could (though writing something myself is certainly still a good learning
> experience).
> 
> On Sep 22, 2015, at 3:51 PM, bsaund <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> I have not heard of JSXGraph.
> I don't know how to plot things in "normal Javascript". This code uses d3.
> You can see the <script> (kind of like an import in other languages) at
> the
> top of "index_copy.html".
> Matt had all the plotting working before I started. I altered some things,
> but mostly I used what he had.
> 
> Javascript does not have classes, and I am not really sure the "best" way
> to get that behavior. You can see I played around with a few different
> ways. One way is with "var" as you mentioned. You can also do some stuff
> with functions. Search for "BuildingDialog" in my code, and notice I
> create
> a new instance with the "new" keyword.
> 
> Repeating lots of code is bad. I think there is a way to do it without
> redefining all the methods every time, at least not explicitly. Let me
> take
> a look and I'll create another pull request.
> 
> On Tue, Sep 22, 2015 at 6:11 PM, skbirner <notifications@github.com<mailto:notifications@github.com>
> mailto:notifications@github.com> wrote:
> 
> > Yeah, I know the feeling. It helped a bit, actually, that I knew my code
> > was messy, so it didn't bother me much to get feedback-- it's scarier
> > presenting code that you're really proud of, because then you feel a lot
> > worse about the criticisms.
> > 
> > Have you heard of or worked with JSXGraph at all (
> > http://jsxgraph.uni-bayreuth.de/wp/)? It looks like it might be a nicer
> > way to do interactive Javascript plots. I'm having a difficult time
> > coming
> > up with nice, succinct ways to plot multiple functions in normal
> > Javascript
> > that don't require copy-pasting large amounts of essentially duplicate
> > code. There are too many inputs to have it work nicely as a function,
> > and
> > Javascript doesn't seem to have classes. The way you guys did it (using
> > a
> > var with methods to build and redraw the data) seems to be the best way,
> > but unless I'm mistaken, it still requires redefining all those methods
> > each and every time you want to plot something.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/skbirner/thermo-website/pull/1#issuecomment-142436668>
> > .
> 
> ## 
> 
> Brad Saund
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142443277>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skbirner/thermo-website/pull/1#issuecomment-142457999
> .

## 

Brad Saund

**Pull request merged**
